import Header from "@/components/Header";
import { DM_Mono } from "next/font/google";


const dmmono = DM_Mono({ weight: "500", subsets: ["latin"] });
export const metadata = {
  title: "k.ap Shorts Url",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmmono.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
